"""empty message

Revision ID: 750640043cd4
Revises: 7e45f53febe1
Create Date: 2021-12-28 22:47:43.270886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "750640043cd4"
down_revision = "7e45f53febe1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings", sa.Column("source", sa.String(length=32), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "source")
    # ### end Alembic commands ###
